name: Lint & Audit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci || npm install
      - name: ESLint
        run: npx next lint --no-cache
      - name: Type check
        run: npx tsc --noEmit
      - name: Next build (dry check)
        run: npm run build

  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    needs: lint
    continue-on-error: true
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Build
        run: npm run build
      - name: Start server
        run: |
          npm run start &
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 > /dev/null; then echo "Server is up"; break; fi
            echo "Waiting for server..."; sleep 2
          done
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:3000/
            http://localhost:3000/solutions
            http://localhost:3000/solutions/omega-match
            http://localhost:3000/solutions/omega-omg
            http://localhost:3000/solutions/omega-omg-vscode
          uploadArtifacts: true
          temporaryPublicStorage: true
