name: Sync Marketing Content

on:
  schedule:
    # Daily at 06:00 UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      owner:
        description: 'GitHub owner/org of the source repositories'
        required: false
        default: 'scholarsmate'
      branch:
        description: 'Branch to fetch from'
        required: false
        default: 'main'
      force:
        description: 'Force a commit even if no content changed (also updates timestamp)'
        required: false
  default: 'true'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Fetch marketing content
        env:
          OMG_OWNER: ${{ github.event_name == 'workflow_dispatch' && inputs.owner || 'scholarsmate' }}
          OMG_BRANCH: ${{ github.event_name == 'workflow_dispatch' && inputs.branch || 'main' }}
        run: |
          node scripts/fetch-marketing.mjs

      - name: Commit and push changes (force optional)
        env:
          FORCE_COMMIT: ${{ github.event_name == 'workflow_dispatch' && inputs.force || 'false' }}
        run: |
          CHANGED_COUNT=$(git status --porcelain content | wc -l)
          echo "Detected changes in content/: ${CHANGED_COUNT}"
          echo "FORCE_COMMIT=${FORCE_COMMIT}"
          if [[ "${FORCE_COMMIT}" == "true" || ${CHANGED_COUNT} -gt 0 ]]; then
            mkdir -p content
            TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            echo "Last marketing sync: ${TS}" > content/LAST_SYNC.md
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add content
            git commit -m "chore(marketing): sync at ${TS} (force=${FORCE_COMMIT}, changes=${CHANGED_COUNT})" || echo "Nothing to commit"
            git push || echo "Nothing to push"
          else
            echo "No changes and not forced; skipping commit."
          fi
